apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true 

configMapGenerator:

- namespace: crossplane-system
  name: pythonic-aks
  options:
    labels:
      function-pythonic.package: ''
  files:
  - kubernetescluster.py
  - resourcegroup.py

resources:
- composition.yaml
- xr.yaml
